version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: tasks-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tasksdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
